name: Dev-Build

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
  workflow_dispatch:

jobs:
  release:
    name: release1
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      id-token: write
      contents: read

    steps:
      - run: echo 'release develop'