name: Main-Build

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
  workflow_call:
    inputs:
      pull_request_number:
        description: 'pull request number'
        required: true
        type: number
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false

env:
  pull_request_number: ${{ github.event.pull_request.number || inputs.pull_request_number }}

jobs:
  release:
    name: release2
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: echo 'release main'
      - run: echo ${{ env.pull_request_number }}